#server:
 # port: 8082
  
#spring:
 # datasource:
  #  driver-class-name: com.mysql.cj.jdbc.Driver
   # url: jdbc:mysql://localhost:3306/wdep?useSSL=false
    #username: root
    #password: root
  #jpa:
   # properties:
    #  hibernate:
     #   dialect: org.hibernate.dialect..MySQLDialect
    #generate-ddl: true
    #show-sql: true
    #hibernate:
     #ddl-auto: update
